#!/bin/bash
set -e

APPLICATION=$1
ONLY_RUN_SWIFT_LINT=$2
USE_APT_GET=$3

if [ "$USE_APT_GET" == 'yes' ]; then
    apt-get update
    apt-get -y install libssl-dev libz-dev
fi

cd /package

cd $APPLICATION

if [ "$ONLY_RUN_SWIFT_LINT" == 'yes' ]; then
    ls
    swiftlint
else
    swift build -c release
    swift test
fi
